public class Teste {
    private decimal altura {get;set;}
    private integer peso {get;set;}
    private decimal mathTeste = 1.03;
    
    public Teste(){
          
    }
    
    public Decimal validaIMC (Decimal alt, Integer p1){
        Decimal IMC;
        return IMC = (p1/ (alt*alt));
    }    
	
    //public class innerTeste(){
     //   String idade {get;set;}
        
        
    //}
}